sudo: required
dist: trusty
group: edge

language: python
cache: pip
python:
  - "3.6"
install:
  - pip install codecov
before_install:
  - sudo apt-get update
jobs:
  include:
  - stage: test
    script: make test && bash <(curl -s https://codecov.io/bash)
