name: buildx

on:
  push:
    branches: master
    tags: 'v*'

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for master
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "master" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.repository == 'cyberreboot/network-tools' && github.event_name == 'push'

    - name: Build and push platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t cyberreboot/mercury:${{ steps.change_version.outputs.VERSION }} mercury && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/ncapture:${{ steps.change_version.outputs.VERSION }} network_tap/ncapture && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/network-tap:${{ steps.change_version.outputs.VERSION }} network_tap && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/p0f:${{ steps.change_version.outputs.VERSION }} p0f && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/pcap-stats:${{ steps.change_version.outputs.VERSION }} pcap_stats && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/pcap-to-node-pcap:${{ steps.change_version.outputs.VERSION }} pcap_to_node_pcap && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/tcprewrite-dot1q:${{ steps.change_version.outputs.VERSION }} tcprewrite_dot1q && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t cyberreboot/snort:${{ steps.change_version.outputs.VERSION }} snort
      if: github.repository == 'cyberreboot/network-tools' && github.event_name == 'push'
